name = "JuliaDot"
uuid = "6e6d1f42-da04-4af2-a797-beb4a2ff0d54"
authors = ["Hiroyuki Okamura"]
version = "0.1.1"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Conda = "1.4"
PyCall = "1.91"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
